dubbo:
  application:
    name: myProvider
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 15000

  protocol:
    id: dubbo
    name: dubbo
    port: 20880
  scan:
    base-packages: com.dubbo.producer.service
server:
  port: 8082
